name: RandomSpawn
main: com.example.randomspawn.RandomSpawnPlugin
version: ${version}
author: You
api-version: "1.20"
description: Randomizes respawn within/just outside nametag distance, avoiding dangerous terrain
